language: node
node_js:
  - 12
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - $TRAVIS_BUILD_DIR/packages/mobile/android/.gradle/caches/
    - $TRAVIS_BUILD_DIR/packages/mobile/android/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/node_modules
branches:
  only:
    - develop
    - feat/ci
notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - nvm install 12
  - node --version
  - travis_retry npm install -g yarn
  - rvm install 2.6.5
  - gem install bundler 
install:
  - cd $TRAVIS_BUILD_DIR/packages/mobile
  - bundle install
  - cd $TRAVIS_BUILD_DIR
  - yarn install

jobs:
  include:
    - language: android
      jdk: oraclejdk8
      dist: precise
      before_cache:
        - rm -f $TRAVIS_BUILD_DIR/packages/mobile/android/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $TRAVIS_BUILD_DIR/packages/mobile/android/.gradle/caches/*/plugin-resolution/
      android:
        components:
          - platform-tools
          - tools
          - build-tools
          - android-28
          - android-29
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      script:
        - cd $TRAVIS_BUILD_DIR/packages/mobile
        - bundle exec fastlane android alpha

    - language: objective-c
      os: osx
      osx_image: xcode11.4
      script:
        - cd $TRAVIS_BUILD_DIR/packages/mobile
        - bundle exec fastlane ios alpha
