language: node
node_js:
  - 12
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - $HOME/packages/mobile/android/.gradle/caches/
    - $HOME/packages/mobile/android/.gradle/wrapper/
    - node_modules
branches:
  only:
    - develop
    - feat/ci
notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - cd packages/mobile
  - bundle install
install:
  - cd $HOME
  - yarn install
script:
  - cd $HOME/packages/common

jobs:
  include:
    - language: android
      jdk: oraclejdk8
      dist: precise
      before_cache:
        - rm -f $HOME/packages/mobile/android/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/packages/mobile/android/.gradle/caches/*/plugin-resolution/
      android:
        components:
          - platform-tools
          - tools
          - build-tools
          - android-28
          - android-29
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      script:
        - cd $HOME/packages/mobile
        - bundle exec fastlane android alpha

    - language: objective-c
      os: osx
      osx_image: xcode11.4
      node_js: false
      cache:
      script:
        - cd $HOME/packages/mobile
        - bundle exec fastlane ios alpha
